from typing import TypedDict
from langchain.messages import AnyMessage
from typing_extensions import TypedDict, Annotated
import operator


class Confidence(TypedDict):
    score: float
    reasoning: str


class Evidence(TypedDict):
    description: str
    reasoning: str
    source_node: str


class Hypothesis(TypedDict):
    hypothesis: str
    evidence: Evidence = None
    confidence: Confidence = None


class MessagesState(TypedDict):
    messages: Annotated[list[AnyMessage], operator.add]
    llm_calls: int


class OneShotCodeGenState(TypedDict, total=False):
    # Input
    problem: str

    # Output
    generated_code: str

    # Intermediates
    hypothesis: str
    evidence: str
    evidence_evaluation: float
    reflection: str

    # Event logging
    history: Annotated[list[dict], operator.add]

    # Optional bookkeeping
    messages: Annotated[list[AnyMessage], operator.add]
    llm_calls: int


class DebuggingState(TypedDict, total=False):
    # The call graph data (nodes, edges, suspiciousness scores)
    call_graph: dict

    # Current node under investigation (FQN)
    target_node: str

    # The inspection code (tests/assertions) generated by the LLM
    inspection_patch: str
    inspection_diff: str

    # The original source code of the function (for restoration)
    original_source: str

    # Results from running the inspection patch
    execution_result: str

    # Reflection on the current step
    reflection: str

    # The final patch generated to fix the bug
    final_patch: str
    final_diff: str

    # Configuration
    score_delta: float
    test_command: str

    # Discovered tests and coverage (Innovation: Fault Localization baseline)
    tests: list[str]  # List of test function FQNs or file paths
    coverage_matrix: dict[str, list[str]]  # Node FQN -> List of Test FQNs that cover it
    
    # Docker Support
    container_id: str
    container_workspace: str
    host_workspace: str
    use_docker: bool

    # Event logging
    history: Annotated[list[dict], operator.add]

    # Bookkeeping
    messages: Annotated[list[AnyMessage], operator.add]
    llm_calls: int
