from typing import TypedDict
from langchain.messages import AnyMessage
from typing_extensions import TypedDict, Annotated
import operator

class DebuggingState(TypedDict, total=False):
    # The call graph data (nodes, edges, suspiciousness scores)
    call_graph: dict

    # Current node under investigation (FQN)
    target_node: str

    # The inspection code (tests/assertions) generated by the LLM
    inspection_patch: str
    inspection_diff: str

    # The original source code of the function (for restoration)
    original_source: str

    # Results from running the inspection patch
    execution_result: str

    # Reflection on the current step
    reflection: str

    # The final patch generated to fix the bug
    final_patch: str
    final_diff: str

    # Configuration
    score_delta: float
    test_command: str

    # Discovered tests and coverage 
    tests: list[str]  # List of test function FQNs or file paths
    coverage_matrix: dict[str, list[str]]  # Node FQN -> List of Test FQNs that cover it
    
    # Docker Support
    container_id: str
    container_workspace: str
    host_workspace: str
    use_docker: bool

    # Event logging
    history: Annotated[list[dict], operator.add]

    # Bookkeeping
    messages: Annotated[list[AnyMessage], operator.add]
    llm_calls: int
